### ISSUE TITLE
Cannot enter Vehicle

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#771] opened 2021-11-03 23:40 UTC
#### __Description__ 
Cannot enter vehicle when unlocked. I could slimjim the door but still could not get in. No errors.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1413.74, -425.8117, 36.15747)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment] 2021-11-04 17:53
Duplicate of #593

**Closed as completed by Dimmies** 2021-11-04 17:53 UTC
Labels: duplicate
