### ISSUE TITLE
Random Minerals appearing

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#176] opened 2021-08-14 22:00 UTC
#### __Description__ 
Was at the toll mart and random minerals started appearing on the fround

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(44.79108, -1748.708, 29.55304)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | VSU81638
**Character Name** | Frank Kirabti

**Comment by Dimmies** [comment] 2021-08-14 22:44
Duplicate of #171

**Closed by Dimmies** 2021-08-14 22:44 UTC
Labels: duplicate
