### ISSUE TITLE
Cant see weed plants.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#211] opened 2021-08-17 23:10 UTC
#### __Description__ 
Planted them last night before I went to bed. Got on today cant see them but I can harvest them
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(283.3646, -649.114, 42.01865)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment] 2021-08-18 04:20
Duplicate of #94

**Comment by Dimmies** [comment] 2021-08-18 06:43
This was an issue with coordinates, but has been fixed

**Closed as completed by Dimmies** 2021-08-18 06:43 UTC
Labels: bug, complete
