### ISSUE TITLE
Steel Pickaxe not producing items.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1283] opened 2022-03-11 22:51 UTC
#### __Description__ 
Steel Pickaxe not producing items when mining in the quarry. Mining animation works but you do not gather any material.
#### __Evidence__ 
https://clips.twitch.tv/YummyFancyStapleDatBoi-et2A5MM7wqqbkmJ2
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | JazyPickle
**Coordinates** | vector3(2953.7, 2769.025, 39.52246)
**Steam ID** | steam:1100001084f8daa
**Discord ID** | discord:303249267403915274
**Citizen ID** | GFU48929
**Character Name** | Jim Packle

**Comment by Dimmies** [comment] 2022-03-15 00:30
Duplicate of #1286

**Closed as completed by Dimmies** 2022-03-15 00:30 UTC
Labels: duplicate
