### ISSUE TITLE
pickaxes

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1316] opened 2022-03-21 07:41 UTC
#### __Description__ 
copper & gold pick axes dont work, dont show uses, only the steel one works
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Tashells
**Coordinates** | vector3(2972.839, 2797.625, 41.22284)
**Steam ID** | steam:1100001080d9f37
**Discord ID** | discord:667668359198015499
**Citizen ID** | QOT21414
**Character Name** | Rosa Martinez

**Comment by Dimmies** [comment] 2022-03-28 17:32
Duplicate of #1286

Should be resolved as of [1.85.0](https://hiverp.net/changelogs)

**Closed as completed by Dimmies** 2022-03-28 17:32 UTC
Labels: bug, complete
