### ISSUE TITLE
Phone

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#663] opened 2021-10-17 01:35 UTC
#### __Description__ 
When i take pictures they are black and when i take a nap it is still doing it and my messages are getting deleted without me deteting them
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | kristafire9178.ttv
**Coordinates** | vector3(143.6048, -3035.592, 7.040891)
**Steam ID** | steam:11000013e8e86cc
**Discord ID** | discord:484116967943438339
**Citizen ID** | IKZ30841
**Character Name** | Cherry Blossome

**Comment by Dimmies** [comment] 2021-11-02 20:34
Duplicate of #629

**Closed as completed by Dimmies** 2021-11-02 20:34 UTC
Labels: duplicate
