### ISSUE TITLE
SG4 rims keep disapearing

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1331] opened 2022-03-28 01:25 UTC
#### __Description__ 
the rims on my sg4 reset if it is impounded or parked in garage

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | StevenBillls
**Coordinates** | vector3(-126.4691, -1137.227, 25.22205)
**Steam ID** | steam:11000013bedcecb
**Discord ID** | discord:501585887096864788
**Citizen ID** | PVF94604
**Character Name** | Ricky Barnes

**Comment by Dimmies** [comment] 2022-04-11 03:22
Duplicate of #1183

**Closed as completed by Dimmies** 2022-04-11 03:22 UTC
Labels: duplicate
