### ISSUE TITLE
missing bike and car

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#429] opened 2021-09-12 16:21 UTC
#### __Description__ 
went into the arcade run around in there looking at the arcade machines come back out side and my bike was misssing it was defo locked i also had this issue down at the lorry place with my car i returned the lorry and my car was gone as well 
#### __Evidence__ 
no clip or screenshot sorry
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | TheBadGuy
**Coordinates** | vector3(-1266.01, -269.4343, 38.92936)
**Steam ID** | steam:11000010b339ff6
**Discord ID** | discord:431958633656483840
**Citizen ID** | EIB50113
**Character Name** | Prince Devitt

**Comment by Dimmies** [comment] 2021-09-13 07:09
Duplicate of #360

**Closed as completed by Dimmies** 2021-09-13 07:09 UTC
Labels: duplicate
