### ISSUE TITLE
Tires popping when pulling cars from garage.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1004] opened 2021-12-15 21:54 UTC
#### __Description__ 
Car is at 95% engine, 90% body
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cain
**Coordinates** | vector3(-1423.264, -447.8121, 35.90966)
**Steam ID** | steam:110000104e5ec26
**Discord ID** | discord:131489989627215872
**Citizen ID** | EMC52102
**Character Name** | Hugh Wiseman

**Comment by Dimmies** [comment] 2021-12-31 02:00
Duplicate of #976

**Closed as completed by Dimmies** 2021-12-31 02:00 UTC
Labels: duplicate
