### ISSUE TITLE
Car Parts

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#865] opened 2021-11-20 12:21 UTC
#### __Description__ 
According to the OBD scanner, my car parts for the Sultan RS are not degrading. I have noticed this same issue with the NRG900 sports bike.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuz
**Coordinates** | vector3(975.6876, 49.79363, 74.68112)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | BFV40301
**Character Name** | Andre Turner

**Comment by Dimmies** [comment] 2021-11-27 00:40
Duplicate of #879

**Closed as completed by Dimmies** 2021-11-27 00:40 UTC
Labels: duplicate
