### ISSUE TITLE
wheels

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1218] opened 2022-02-17 00:58 UTC
#### __Description__ 
repaired my vehicle 2x both times lost wheels and custom tires.. once was using an advance repair kit, and the second time was at bennys.. not too bothered about the $$ just thought id make a bug report.. thanks for all you guys do for the city. <3 Frankie 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Rowes
**Coordinates** | vector3(346.1798, -2638.927, 5.935408)
**Steam ID** | steam:11000013d4a2d48
**Discord ID** | discord:689724306984665098
**Citizen ID** | DHT92792
**Character Name** | Frankie Rowes

**Comment by Dimmies** [comment] 2022-04-11 03:21
Duplicate of #1183

**Closed as completed by Dimmies** 2022-04-11 03:21 UTC
Labels: duplicate
