### ISSUE TITLE
Client Errors

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#68] opened 2021-07-19 16:35 UTC
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
https://i.imgur.com/MfHza0L.png | https://i.imgur.com/KrMi3Cl.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(481.0391, -995.4169, 30.68983)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment] 2021-07-20 03:48
Looks like it's all polylook related and it's all coming from criminal scripts. hive-polylook was starting AFTER criminal stuff was starting so I moved it to start with the core files, this should possibly fix these errors and even possibly #14

**Comment by Dimmies** [comment] 2021-07-20 11:25
Confirmed to be fixed now

**Closed by Dimmies** 2021-07-20 11:25 UTC
Labels: bug, complete
