### ISSUE TITLE
Storing vehicles

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#513] opened 2021-09-19 20:48 UTC
#### __Description__ 
I cant store my motorcycle or my car, it shows me the message saying "Press E" but when I press it it does nothing
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | WhoOwl
**Coordinates** | vector3(133.1656, -965.1971, 28.83238)
**Steam ID** | steam:1100001423b37be
**Discord ID** | discord:808037183255609385
**Citizen ID** | ZZI27864
**Character Name** | Manny Glanton

**Comment by Dimmies** [comment] 2021-09-20 09:46
Duplicate of #419

**Closed as completed by Dimmies** 2021-09-20 09:46 UTC
Labels: duplicate
