### ISSUE TITLE
see other players when they are in their appartment when ur in your appartment

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#275] opened 2021-08-23 17:11 UTC
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(255.724, -638.8876, 40.40615)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment] 2021-08-24 01:25
Duplicate of #210

**Closed as completed by Dimmies** 2021-08-24 01:25 UTC
Labels: duplicate
