### ISSUE TITLE
Ped Characters

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#866] opened 2021-11-20 19:10 UTC
#### __Description__ 
Ped Characters spawn as half health
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuz
**Coordinates** | vector3(-348.7622, -654.8075, -56.92728)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | AUM87461
**Character Name** | Shanice Robinson

**Comment by Dimmies** [comment] 2021-12-15 01:32
Duplicate of #605

**Closed as completed by Dimmies** 2021-12-15 01:32 UTC
Labels: duplicate
