### ISSUE TITLE
Casino Prize Wheel crash

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#514] opened 2021-09-19 20:49 UTC
#### __Description__ 
Experienced (CTD) crash to desktop while spinning casino prize wheel, no FiveM crashlog.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuz
**Coordinates** | vector3(976.4676, 50.31208, 74.67676)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | BFV40301
**Character Name** | Andre Turner

**Comment by zeuzible** [comment] 2021-09-19 23:08
To add onto this, after coming loading back in last location I was able to continue spinning the prize wheel without another crash.

**Comment by Dimmies** [comment] 2021-09-22 23:57
Duplicate of #512

**Closed as completed by Dimmies** 2021-09-22 23:57 UTC
Labels: duplicate
