### ISSUE TITLE
Plastic surgery and hair failing to save to the database.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1153] opened 2022-01-27 03:35 UTC
#### __Description__ 
Every time I load in, Brett Lawson's facial features, hair, and skin color aren't saving to the database.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | NadeFrame
**Coordinates** | vector3(142.2644, -3020.302, 7.040891)
**Steam ID** | steam:110000110adcb80
**Discord ID** | discord:262487501434912768
**Citizen ID** | DGV32947
**Character Name** | Malique Patrone

**Comment by Dimmies** [comment] 2022-02-28 00:20
Duplicate of #630

**Closed as completed by Dimmies** 2022-02-28 00:20 UTC
Labels: duplicate
