### ISSUE TITLE
take a look at jerry cans, tupa and I both couldnt get them to fill up a vehicle

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#440] opened 2021-09-13 04:46 UTC
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(923.5014, 47.60061, 81.10643)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment] 2021-09-13 07:08
Duplicate of #423

**Closed as completed by Dimmies** 2021-09-13 07:08 UTC
Labels: duplicate
