### ISSUE TITLE
Cannot store Vehicle

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#886] opened 2021-11-26 05:45 UTC
#### __Description__ 
Cannot store vehicle at garage and can then go to the vehcile spawn and dupe that vehicle. This is at Pillbox/Square parking lot.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(222.2006, -802.6938, 30.09042)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment] 2021-11-26 05:48
Cannot impound, DV or storeplate either.

**Comment by eamundson1** [comment] 2021-11-26 06:03
Cannot impound, DV or storeplate either.

**Comment by Dimmies** [comment] 2021-11-27 00:17
Duplicate of #419

**Closed as completed by Dimmies** 2021-11-27 00:17 UTC
Labels: duplicate
