### ISSUE TITLE
Losing Slushies when leaving prison

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1073] opened 2022-01-02 09:12 UTC
#### __Description__ 
When items acquired in prison are in slots that were previously occupied they might become deleted, when released from prison.
#### __Evidence__ 
N/A
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Delta
**Coordinates** | vector3(1854.301, 2582.136, 45.66792)
**Steam ID** | steam:11000010270ecf3
**Discord ID** | discord:87332850298273792
**Citizen ID** | YKP34355
**Character Name** | Darryl Wilson

**Comment by Dimmies** [comment] 2022-02-27 23:42
Duplicate of #1028

**Closed as completed** 2022-02-27 23:42 UTC
Labels: duplicate
