### ISSUE TITLE
Sentinel SG4 Upgrades

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1201] opened 2022-02-13 01:57 UTC
#### __Description__ 
My sentinel sg4 does not have any of the stuff on it. Like spoiler rims tint 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | StevenBillls
**Coordinates** | vector3(130.0448, -1284.856, 29.26933)
**Steam ID** | steam:11000013bedcecb
**Discord ID** | discord:501585887096864788
**Citizen ID** | PVF94604
**Character Name** | Ricky Barnes

**Comment by Dimmies** [comment] 2022-02-13 18:28
Duplicate of #1186

**Closed as completed by Dimmies** 2022-02-13 18:28 UTC
Labels: duplicate
