### ISSUE TITLE
Cannot get in car

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#821] opened 2021-11-12 23:44 UTC
#### __Description__ 
Cannot get in vehicle after it is unlocked or slimjimmed.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-233.3486, -665.9484, 33.37423)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment] 2021-11-27 00:01
Duplicate of #593

**Closed as completed by Dimmies** 2021-11-27 00:01 UTC
Labels: duplicate
