### ISSUE TITLE
fixing face at surgeon reverted my facec to default

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#998] opened 2021-12-15 02:36 UTC
#### __Description__ 
I had silver hair and a facial preset i had saved but changing my butt chin problem caused the hair color to revert to default as well as facial features.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Britamins
**Coordinates** | vector3(307.8917, -589.696, 43.2841)
**Steam ID** | steam:110000133272d55
**Discord ID** | discord:156579090315345920
**Citizen ID** | MHP48555
**Character Name** | Briten Clark

**Comment by Dimmies** [comment] 2022-02-28 00:19
Duplicate of #630

**Closed as completed by Dimmies** 2022-02-28 00:19 UTC
Labels: duplicate
