### ISSUE TITLE
Phone scuff?

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#977] opened 2021-12-10 02:46 UTC
#### __Description__ 
Seems the phone bugged upon logging in. Background is gone, and apps have notifs with 0's.
#### __Evidence__ 
https://i.imgur.com/6D3Dk1S.png
https://i.imgur.com/GsU427j.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | NadeFrame
**Coordinates** | vector3(161.1671, -1252.328, 28.85151)
**Steam ID** | steam:110000110adcb80
**Discord ID** | discord:262487501434912768
**Citizen ID** | DGV32947
**Character Name** | Malique Hendrix

**Comment by Dimmies** [comment] 2022-01-13 12:33
Duplicate of #716

**Closed as completed by Dimmies** 2022-01-13 12:33 UTC
Labels: duplicate
