### ISSUE TITLE
Casino Wheel

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#733] opened 2021-10-28 23:27 UTC
#### __Description__ 
Paid 500 and won 500 but did not receive 500.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(428.6774, -498.0216, 136.3209)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by Dimmies** [comment] 2022-01-13 12:10
Duplicate of #619

**Closed as completed by Dimmies** 2022-01-13 12:10 UTC
Labels: duplicate
