### ISSUE TITLE
Issue with the ~ key not showing recent calls

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#304] opened 2021-08-29 04:00 UTC
#### __Description__ 
For some, the ~ changes the volume of speech, so maybe that has something to do with it not working Dimmies
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(270.902, -319.1176, 44.72888)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | USC02137
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment] 2021-08-30 21:08
Duplicate of #285

**Closed as completed by Dimmies** 2021-08-30 21:08 UTC
Labels: duplicate
