### ISSUE TITLE
Random Items Spawning

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#173] opened 2021-08-14 21:13 UTC
#### __Description__ 
Items are randomly spawning on the ground (the yellow/orange arrow indicating something is on the ground). I think it's when someone is overweight and their items are supposed to drop at their feet. Had mining ores randomly drop at my feet multiple times whilst in the city.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chuff
**Coordinates** | vector3(-133.0847, -926.4479, 28.56674)
**Steam ID** | steam:110000101c301ed
**Discord ID** | discord:147386472016642058
**Citizen ID** | FHO94294
**Character Name** | Tommy Jenkins

**Comment by Dimmies** [comment] 2021-08-14 22:45
Duplicate of #171

**Closed by Dimmies** 2021-08-14 22:45 UTC
Labels: duplicate
