### ISSUE TITLE
Fishing Rod drops on ground and piles up

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#258] opened 2021-08-21 23:31 UTC
#### __Description__ 
everytime you cast you drop a rod on the ground and they just pile up

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Silver_Twist86
**Coordinates** | vector3(-1730.687, -1058.863, 0.9976513)
**Steam ID** | steam:110000104ca4df2
**Discord ID** | discord:215280083957448704
**Citizen ID** | JRX14884
**Character Name** | Bryan Stone

**Comment by Dimmies** [comment] 2021-08-28 18:07
Duplicate of #226

**Closed as completed by Dimmies** 2021-08-28 18:07 UTC
Labels: bug, unconfirmed
