### ISSUE TITLE
hunting

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#426] opened 2021-09-12 10:14 UTC
#### __Description__ 
Once Bait is placed, you wait the time and no matter what you do the animal gets scared off, a second prompt comes up shorlty after saying something is approaching but nothing shows up/
#### __Evidence__ 
https://cdn.discordapp.com/attachments/876141775448854568/886555441272852490/unknown.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | iTzHoBBs
**Coordinates** | vector3(-769.4044, 5283.485, 87.59788)
**Steam ID** | steam:110000103ebb8a4
**Discord ID** | discord:386139575782998017
**Citizen ID** | WQM70520
**Character Name** | Martin Riggs

**Comment by Dimmies** [comment] 2021-09-13 07:12
Duplicate of #422

**Closed as completed by Dimmies** 2021-09-13 07:12 UTC
Labels: duplicate
