### ISSUE TITLE
Weapons License

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#811] opened 2021-11-11 03:50 UTC
#### __Description__ 
Earlier in the day around 4PM EST, I was given a Weapons License by Undersheriff Saint (Cody) Now at 10:48PM EST I am checking the gun stor to buy a wrench but realize it says I have no license and that the weapons are not available for me to purchase.
#### __Evidence__ 
https://i.imgur.com/ucQvcdT.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dopykoh.TTV
**Coordinates** | vector3(21.12683, -1106.58, 29.79703)
**Steam ID** | steam:11000011376e182
**Discord ID** | discord:193681533620584448
**Citizen ID** | VJG97234
**Character Name** | Jose Fernandez

**Comment by Dimmies** [comment] 2021-11-11 16:21
Duplicate of #805

**Closed as completed by Dimmies** 2021-11-11 16:21 UTC
Labels: duplicate
