### ISSUE TITLE
cannot sit on my bike

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1552] opened 2022-07-20 11:37 UTC
#### __Description__ 
hey, a connot sit back on my bike once i get up of it like it's locked, but i checked if it's unlocked. no such broblems with other ones
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dino
**Coordinates** | vector3(902.5699, -1737.454, 30.16248)
**Steam ID** | steam:11000010471c4d3
**Discord ID** | discord:709876723105398834
**Citizen ID** | ZGJ27832
**Character Name** | Alex Orison

**Comment by Dimmies** [comment] 2022-08-07 22:42
duplicate of #1498

**Closed as completed by Dimmies** 2022-08-07 22:42 UTC
Labels: duplicate
