### ISSUE TITLE
police vigero not spawning with sheriffs dept livery

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#313] opened 2021-08-29 06:02 UTC
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(178.0468, -1012.341, 29.25178)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment] 2021-08-29 18:07
Duplicate of #268

**Closed as completed by Dimmies** 2021-08-29 18:07 UTC
Labels: duplicate
