### ISSUE TITLE
Head pops during Metal Detecting

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1317] opened 2022-03-21 09:40 UTC
#### __Description__ 
Seems to happen when given a specific spot. You don't need to start digging for the head pop to happen, it happens when you get close. Screenshots linked show error message, plus two shots of the general area where the head pops happen. Can't get a specific location without headpopping, haha. 
#### __Evidence__ 
https://i.gyazo.com/24b79297908d6e22c05941630d3f041f.png  -  https://i.gyazo.com/b0bd28e4799c08c5cee5cd0b37dd15bb.png  -  https://i.gyazo.com/8c242a0b66c1eeadb09556ac1a32e2bf.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | NervousFluff
**Coordinates** | vector3(-1501.714, -1258.334, 2.365939)
**Steam ID** | steam:1100001030a0585
**Discord ID** | discord:186814870463709185
**Citizen ID** | HAM96109
**Character Name** | Phoebe Telford

**Comment by Dimmies** [comment] 2022-03-28 17:36
Duplicate of #1315

**Closed as completed by Dimmies** 2022-03-28 17:36 UTC
Labels: duplicate
