### ISSUE TITLE
Car Boosting

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#396] opened 2021-09-09 18:09 UTC
#### __Description__ 
After boosting car, beeing battered by a local with a bat and coming back to simeons he is saying its not the car he was looking for. think he's wrong
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | VisionzAx
**Coordinates** | vector3(-1154.35, -2002.588, 12.42508)
**Steam ID** | steam:110000136d79dfe
**Discord ID** | discord:527475418299629568
**Citizen ID** | BRI89099
**Character Name** | Kilo Broker

**Comment by Dimmies** [comment] 2021-09-09 21:01
Duplicate of #328

**Closed as completed by Dimmies** 2021-09-09 21:01 UTC
Labels: duplicate
