### ISSUE TITLE
Car Door won't unlock

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#863] opened 2021-11-20 04:50 UTC
#### __Description__ 
Stolen car door was acting fine for an hour or so but now won't unlock.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(239.2664, -668.2632, 37.98267)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by eamundson1** [comment] 2021-11-20 05:19
Also noticed that the horn sound is very inconsistent and mostly not sounding.

**Comment by Dimmies** [comment] 2021-11-27 00:08
Duplicate of #593

For the horn bug, please open another bug report

**Closed as completed by Dimmies** 2021-11-27 00:08 UTC
Labels: duplicate
