### ISSUE TITLE
Car Upgrades

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#235] opened 2021-08-19 02:22 UTC
#### __Description__ 
Sometimes when you crash or log your upgrades can disapper on the car you own
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | xBrodyxS
**Coordinates** | vector3(-63.8927, -1070.769, 27.01942)
**Steam ID** | steam:11000010c834ebf
**Discord ID** | discord:424994252775358465
**Citizen ID** | THQ84246
**Character Name** | Treyvon Williams

**Comment by Dimmies** [comment] 2021-08-19 16:55
Duplicate of #235

**Closed as completed by Dimmies** 2021-08-19 16:55 UTC
Labels: duplicate
