### ISSUE TITLE
Prison Pocket Wipe

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#891] opened 2021-11-26 23:37 UTC
#### __Description__ 
Prison is still taking peoples stuff permanetly into the Void evey once in a while. I have had this happen several times in the last week 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | TTV-ChairWarrior16
**Coordinates** | vector3(245.7573, -656.2833, 38.3064)
**Steam ID** | steam:1100001125860c8
**Discord ID** | discord:191247899043037184
**Citizen ID** | EWX30031
**Character Name** | Xacarius Henrik

**Comment by Dimmies** [comment] 2021-11-27 00:19
Duplicate of #859

**Closed as completed by Dimmies** 2021-11-27 00:19 UTC
Labels: bug, unconfirmed
