### ISSUE TITLE
Spawn bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#222] opened 2021-08-18 02:41 UTC
#### __Description__ 
Spawned in at the last loaction of the apt and fell throguh the arth but did arrive in the tunnel underneath
#### __Evidence__ 
https://steamcommunity.com/sharedfiles/filedetails/?id=2577961847
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(334.175, -672.3271, 29.25972)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by Dimmies** [comment] 2021-08-28 18:05
Duplicate of #178

**Closed as completed by Dimmies** 2021-08-28 18:05 UTC
Labels: duplicate
