### ISSUE TITLE
Missing Vehicle

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#435] opened 2021-09-12 23:21 UTC
#### __Description__ 
Went out on a call for a tow, when I got back to the mechanic shop my bike was gone. Wasn't in the garage, wasn't impounded. Presumed stolen but heard people have had issues with vehicles vanishing. Whilst doing the mechanic job I've experienced not being able to unlock my own vehicle after having to jimmy a car open or being in a car I'm recovering. Feels like I'm missing part of the ownership of my own vehicle - just thought it might have something to do with that.
#### __Evidence__ 
https://imgur.com/RZ8MI9s
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chuff
**Coordinates** | vector3(-84.31992, -1323.745, 29.28408)
**Steam ID** | steam:110000101c301ed
**Discord ID** | discord:147386472016642058
**Citizen ID** | FHO94294
**Character Name** | Tommy Jenkins

**Comment by Dimmies** [comment] 2021-09-13 07:10
Duplicate of #360

**Closed as completed by Dimmies** 2021-09-13 07:10 UTC
Labels: duplicate
