### ISSUE TITLE
Gas not depleting from cars after drifting

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1195] opened 2022-02-12 06:09 UTC
#### __Description__ 
I was drifting earlier and the drift script makes it to where fuel doesn't deplete. Now fuel doesn't deplete from any car I drive.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | NadeFrame
**Coordinates** | vector3(-679.2762, 704.2593, 154.2881)
**Steam ID** | steam:110000110adcb80
**Discord ID** | discord:262487501434912768
**Citizen ID** | DGV32947
**Character Name** | Malique Patrone

**Comment by Dimmies** [comment] 2022-02-13 18:40
Duplicate of #1194

**Closed as completed by Dimmies** 2022-02-13 18:40 UTC
Labels: duplicate
