### ISSUE TITLE
UI elements

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1051] opened 2021-12-27 07:38 UTC
#### __Description__ 
Optimize UI elements to scale appropriately on different resolutions (other than 1920x1080)
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuzible
**Coordinates** | vector3(437.3833, -983.3344, 30.68958)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | UKD42498
**Character Name** | Adam Hall

**Comment by Dimmies** [comment] 2022-01-13 12:50
Duplicate of #883

**Closed as completed by Dimmies** 2022-01-13 12:50 UTC
Labels: duplicate
