### ISSUE TITLE
Vehicle damaged when taking it out of the garage.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1064] opened 2021-12-30 21:39 UTC
#### __Description__ 
Everytime you get a vehicle from the garage by integrity it breaks all your windows and pops tire or breaks all the windows and your car is smoking. 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | DimBagDimez
**Coordinates** | vector3(224.6938, -814.0513, 30.32116)
**Steam ID** | steam:110000141b3085e
**Discord ID** | discord:712785321481469994
**Citizen ID** | NQP90955
**Character Name** | Dimez DAmico

**Comment by Dimmies** [comment] 2021-12-31 02:02
Duplicate of #976

**Closed as completed by Dimmies** 2021-12-31 02:02 UTC
Labels: duplicate
