### ISSUE TITLE
Radio

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#286] opened 2021-08-24 03:51 UTC
#### __Description__ 
Can hear radio clicks once someone takes away my radio.. only now in prison and can't hear the person on the radio 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | xBrodyxS
**Coordinates** | vector3(1763.822, 2540.873, 45.565)
**Steam ID** | steam:11000010c834ebf
**Discord ID** | discord:424994252775358465
**Citizen ID** | THQ84246
**Character Name** | Treyvon Williams

**Comment by Dimmies** [comment] 2021-08-24 19:12
Duplicate of #252

**Closed as completed** 2021-08-24 19:12 UTC
Labels: duplicate
