### ISSUE TITLE
Dropping items 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#288] opened 2021-08-25 01:25 UTC
#### __Description__ 
When dropping items over time they stay there.. could be a issue if someone picks up a item from an item dropped because marker wont disappear till restart 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | xBrodyxS
**Coordinates** | vector3(104.7416, -1397.681, 29.28697)
**Steam ID** | steam:11000010c834ebf
**Discord ID** | discord:424994252775358465
**Citizen ID** | UBD72148
**Character Name** | Rudy Domino

**Comment by Dimmies** [comment] 2021-08-30 20:59
Duplicate of #262

**Closed as completed by Dimmies** 2021-08-30 20:59 UTC
Labels: duplicate
