### ISSUE TITLE
Vehicle Persistence

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#750] opened 2021-10-31 05:16 UTC
#### __Description__ 
Some of the Cars are technically there, but not. They flash, break all the windows, and disappear after a second. They will do this every 15-30 seconds randomly, repeating the same steps. Additionally, it does not seem like proximity will keep a car in the location left. My squad car disappeared while I was less than 100 feet away
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(445.5826, -1020.023, 28.55756)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | USC02137
**Character Name** | Pyotr Palach

**Comment by eamundson1** [comment] 2021-10-31 16:44
I have noticed local vehicles flashing and then disappear. Particularly the ones that are seen parked in certain areas.

**Comment by eamundson1** [comment] 2021-10-31 18:19
Vehicles have definitely gotten worse. The last 2 days locks are problematic. Vehicle are disappearing and reappearing and glass breaking.

**Comment by Dimmies** [comment] 2021-11-26 23:47
Duplicate of #360

Still working on it 🙏

**Closed as completed by Dimmies** 2021-11-26 23:47 UTC
Labels: duplicate
