### ISSUE TITLE
Hayes custom horns 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1282] opened 2022-03-11 21:28 UTC
#### __Description__ 
Some Hayes custom horns just sound like normal horns
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | dovesi
**Coordinates** | vector3(-1422.061, -450.2602, 35.90966)
**Steam ID** | steam:11000010569bde9
**Discord ID** | discord:126185398345924609
**Citizen ID** | JVG50155
**Character Name** | Dove Daniels

**Comment by Dimmies** [comment] 2022-04-11 03:24
Duplicate of #1223

**Closed as completed by Dimmies** 2022-04-11 03:24 UTC
Labels: duplicate
