### ISSUE TITLE
Cannot store vehicle

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#662] opened 2021-10-17 01:29 UTC
#### __Description__ 
Attempting to store my vehicle in the Pink Motel Garage, and it will not allow me to store it. No error message, just nothing when I press E.
#### __Evidence__ 
http://img.firav.us/images/2021/10/16/FiveM_b2189_GTAProcess_2021-10-16_21-28-37.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Firav
**Coordinates** | vector3(289.5783, -340.3627, 44.48625)
**Steam ID** | steam:110000106bee631
**Discord ID** | discord:255140640965263360
**Citizen ID** | TPZ08138
**Character Name** | Kevin Baumann

**Comment by Dimmies** [comment] 2021-11-02 20:32
Duplicate of #419

**Closed as completed by Dimmies** 2021-11-02 20:32 UTC
Labels: duplicate
