### ISSUE TITLE
Roxanne not accepting Upgrades

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1189] opened 2022-02-11 21:08 UTC
#### __Description__ 
Roxanne is currently refusing Performance upgrades ask Billy Blue or Curtis for more info
#### __Evidence__ 
F8 console showed nothing notable
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Quacky
**Coordinates** | vector3(131.4137, -3038.852, 7.040893)
**Steam ID** | steam:1100001098aad13
**Discord ID** | discord:211251873573896192
**Citizen ID** | LAN34324
**Character Name** | Devon Camorra

**Comment by Dimmies** [comment] 2022-02-11 23:22
Duplicate of #1186

**Closed as completed by Dimmies** 2022-02-11 23:22 UTC
Labels: duplicate
