### ISSUE TITLE
fishing bar is to fast for some people

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#30] opened 2021-07-14 06:02 UTC
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(1350.203, -551.925, 74.1195)
Steam ID | steam:11000010079352b
Discord ID | discord:216718685883203584
Citizen ID | IEO17773

**Comment by Dimmies** [comment] 2021-07-16 01:00
Duplicate of #19

**Closed by Dimmies** 2021-07-16 01:00 UTC
Labels: unconfirmed
