### ISSUE TITLE
Casino Wheel Consumed a Spin Then Doubled What The Next Spin Landed On

### ISSUE THREAD

**Issue by Wref9058** [TheHiveRP/HiveIssues#812] opened 2021-11-11 13:19 UTC
**Describe the bug**
The first spin of the wheel happened as it normally does (got nothing). On the second spin, the wheel landed on "free spin" three times before landing on $1500. On the third spin, the wheel took the money but did not spin; my character didn't do the spin animation nor did the wheel spin on its own. The next spin took another $500, landed on $1000 and gave me two payouts of that amount, showing +$1000 twice on the HUD. The wheel allowed me one more spin (got nothing) before telling me I hit my limit for the day.

**To Reproduce**
Because the wheel's mechanics are based on chance, it'll be difficult for a player to replicate. It's likely the wheel has to land on "free spin" two or more times before the bug can be replicated on the next spin.

**Expected behavior**
I expected the wheel to spin as it does, which usually lands on nothing (lol).

**Screenshots**
I have an OBS recording uploaded to YouTube, from the moment I get to the wheel to when I walk away from it. Here is the link:

https://www.youtube.com/watch?v=cne4cS7jqbM

0:42 The wheel takes the money and doesn't spin
0:53 The next payout is doubled

**Comment by Dimmies** [comment] 2022-01-13 12:19
Duplicate of #619

**Closed as completed by Dimmies** 2022-01-13 12:19 UTC
Labels: bug, duplicate
