### ISSUE TITLE
House robberies removing all prompts, forcing you to get stuck.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#536] opened 2021-09-22 06:35 UTC
#### __Description__ 
I had 2 different occasions this happened on. First time I broke into a house, and once i tried to access one of the "Search" options it instantly vanished, and so did every other prompt within the house, I tried exiting but that prompt was gone to which resulted in me being stuck inside of this house robbery. The second time, I did the exact same thing, however this time it let me access one of the Search options, but after that one it just repeated the last event and I was stuck in here without any possible prompts again.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | sensu
**Coordinates** | vector3(256.7244, -1680.183, -13.05052)
**Steam ID** | steam:11000010b3c8d3b
**Discord ID** | discord:854934815816024086
**Citizen ID** | IQR64353
**Character Name** | Kai Jung

**Comment by Dimmies** [comment] 2021-09-22 17:51
Duplicate of #534

**Closed as completed by Dimmies** 2021-09-22 17:51 UTC
Labels: duplicate
