### ISSUE TITLE
Vehicle flicke and tire pop when gotten from garage

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1047] opened 2021-12-26 01:41 UTC
#### __Description__ 
When I retrieved my vehicle from Sandy, it flickered and the front tire popped. F8 showed no error but did say
Nitro Fuel 0
I pulled my jeep out, at the square, and had the same flicker happen. I noticed that the amount of gas was different in the jeep before it blinked out than when it blinked back.
I think Karen ended up spawning an extra heli that caused the explosion.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(1737.588, 3721.392, 33.43019)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment] 2021-12-31 02:01
Duplicate of #976

**Closed as completed by Dimmies** 2021-12-31 02:01 UTC
Labels: duplicate
