### ISSUE TITLE
Vehicle wont unlock

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#708] opened 2021-10-25 14:07 UTC
#### __Description__ 
I drove my car to a parking space, left it there for a good while and came back tried to unlock it and it didnt do anything.
#### __Evidence__ 
.
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Mihaiel
**Coordinates** | vector3(246.3895, -648.7322, 39.39838)
**Steam ID** | steam:110000109b7930c
**Discord ID** | discord:194170817913946112
**Citizen ID** | TVY59302
**Character Name** | Jax Reese

**Comment by Dimmies** [comment] 2021-10-28 18:43
#### __Description__ 
Locked my vehicle while it was out, returned to it and i'm unable to unlock and get into it despite notif telling me it's unlocked. 
#### __Evidence__ 
https://i.ibb.co/6RdRQgP/image.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | optimuskel
**Coordinates** | vector3(20.58869, -1879.927, 22.92355)
**Steam ID** | steam:110000113ae38ab
**Discord ID** | discord:373132494264074240
**Citizen ID** | SFN81264
**Character Name** | Olive Fontaine

**Comment by Dimmies** [comment] 2021-11-04 17:51
Duplicate of #593

**Closed as completed by Dimmies** 2021-11-04 17:51 UTC
Labels: duplicate
