### ISSUE TITLE
Items got wiped after leaving prison

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1167] opened 2022-02-02 03:06 UTC
#### __Description__ 
items in inventory while in prison were removed when released. This character was put in prison before the prison item update was rolled out, so it was likely due to that
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | MusicManPrank
**Coordinates** | vector3(91.3865, -189.1926, 54.86773)
**Steam ID** | steam:110000112933c9d
**Discord ID** | discord:199027703762911242
**Citizen ID** | HIE90711
**Character Name** | Richard Umthondo

**Comment by douth-c-archive** [comment] 2022-02-02 18:18
This would need to be a comp request. Due to the info, the bug report can most likely be closed; there's no true bug here since the client was already in prison before a fix was issued.

**Comment by Dimmies** [comment] 2022-02-28 00:05
Duplicate of #1028

**Closed as completed by Dimmies** 2022-02-28 00:05 UTC
Labels: duplicate
