### ISSUE TITLE
Garage bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1063] opened 2021-12-30 19:41 UTC
#### __Description__ 
I tried pulling my car out of the garage, it took out a similar one, stalled the engine & failed (and popped tire), didn't give me keys. So I tried this again, same thing happened. On the third try, it pulled out the right color car this time, didn't stall, but didn't give me keys
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Murci
**Coordinates** | vector3(239.9602, -805.2138, 29.89861)
**Steam ID** | steam:11000011630e157
**Discord ID** | discord:177535063741825024
**Citizen ID** | MHX93241
**Character Name** | Joshua Reinhardt

**Comment by Dimmies** [comment] 2021-12-31 02:03
Duplicate of #976

**Closed as completed by Dimmies** 2021-12-31 02:03 UTC
Labels: duplicate
