### ISSUE TITLE
Garage Bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#682] opened 2021-10-20 04:48 UTC
#### __Description__ 
Legion garage and no other garage won't let me store my personal vehicle
#### __Evidence__ 
https://i.imgur.com/epU7VLL.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | NadeFrame
**Coordinates** | vector3(224.7167, -819.4489, 30.03263)
**Steam ID** | steam:110000110adcb80
**Discord ID** | discord:262487501434912768
**Citizen ID** | QPY65340
**Character Name** | Drake Carter

**Comment by Dimmies** [comment] 2021-11-02 20:40
Duplicate of #419

**Closed as completed by Dimmies** 2021-11-02 20:40 UTC
Labels: duplicate
