### ISSUE TITLE
Hair

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1129] opened 2022-01-17 07:17 UTC
#### __Description__ 
When logging in the hair is set to a hair style not, previously, chosen.

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(490.5167, 5702.398, 727.8527)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment] 2022-02-28 00:20
Duplicate of #630

**Closed as completed by Dimmies** 2022-02-28 00:20 UTC
Labels: duplicate
