### ISSUE TITLE
FAKE PLATES 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#749] opened 2021-10-31 03:24 UTC
#### __Description__ 
If you put a fake plate on a car and you put the car in the garage with the fake plate it wont put your car back into the garage but spawn the car where you last put the fake plate!
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | ✪Prior
**Coordinates** | vector3(124.8307, -3045.637, 7.040889)
**Steam ID** | steam:110000117aeceb1
**Discord ID** | discord:123004172554469376
**Citizen ID** | JFI47802
**Character Name** | Alex Gonzalez

**Comment by Dimmies** [comment] 2021-11-02 21:05
Duplicate of #745

**Closed as completed by Dimmies** 2021-11-02 21:05 UTC
Labels: duplicate
