### ISSUE TITLE
Car not going in the garage

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#824] opened 2021-11-13 06:57 UTC
#### __Description__ 
I went to put my car in the legion garage but it would go in. I spammed E, tried getting in and out unlocking and locking it but it didn't go in the garage
#### __Evidence__ 
https://clips.twitch.tv/GracefulSmoothShallotPipeHype-2izfMxiE7mk7Q1E4
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | overdoseoftoast
**Coordinates** | vector3(361.5005, -581.1992, 44.19276)
**Steam ID** | steam:110000136789e30
**Discord ID** | discord:554398664441856002
**Citizen ID** | UFO57607
**Character Name** | Issac Brown

**Comment by Dimmies** [comment] 2021-11-27 00:01
Duplicate of #419

**Closed as completed by Dimmies** 2021-11-27 00:01 UTC
Labels: duplicate
