### ISSUE TITLE
Getting into personal car

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#828] opened 2021-11-14 00:25 UTC
#### __Description__ 
After i relogged i tried to unlock my car but did not on lock only locked 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Angelz87x
**Coordinates** | vector3(902.6145, 21.33165, 79.23935)
**Steam ID** | steam:1100001023640c5
**Discord ID** | discord:153515217563811840
**Citizen ID** | BLV22370
**Character Name** | Roan Wade

**Comment by Dimmies** [comment] 2021-11-27 00:02
Duplicate of #593

**Closed as completed by Dimmies** 2021-11-27 00:02 UTC
Labels: bug, complete
