### ISSUE TITLE
Random spawn Second time

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#181] opened 2021-08-15 04:45 UTC
#### __Description__ 
Disconnected the same place andflew through air and ended up at You Tool/Tool Mart.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(23.25027, -1727.75, 29.28803)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | VSU81638
**Character Name** | Frank Kirabti

**Comment by Dimmies** [comment] 2021-08-15 15:51
Duplicate of #178

**Closed by Dimmies** 2021-08-15 15:51 UTC
Labels: bug, unconfirmed
