### ISSUE TITLE
Lost items after prison time

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1026] opened 2021-12-18 04:01 UTC
#### __Description__ 
I had both my phone and radio when I was sentenced, once released I lost both but nothing else
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | grill
**Coordinates** | vector3(1840.866, 2585.5, 46.01435)
**Steam ID** | steam:11000010569bde9
**Discord ID** | discord:126185398345924609
**Citizen ID** | FQX28458
**Character Name** | Delfina DeLeon

**Comment by Dimmies** [comment] 2022-02-27 23:40
Duplicate of #1028

**Closed as completed by Dimmies** 2022-02-27 23:40 UTC
Labels: duplicate
