### ISSUE TITLE
Hair colour change

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1138] opened 2022-01-20 12:23 UTC
#### __Description__ 
Every so often when I change my outfit, my hair colour and/or hairstyle reverts to the colour I picked when I first made the character.
#### __Evidence__ 
Sorry! Didn't take any VODs or screnshots.
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | NervousFluff
**Coordinates** | vector3(-1207.123, -786.6911, 16.26382)
**Steam ID** | steam:1100001030a0585
**Discord ID** | discord:186814870463709185
**Citizen ID** | HAM96109
**Character Name** | Phoebe Telford

**Comment by Dimmies** [comment] 2022-02-28 00:20
Duplicate of #630

**Closed as completed by Dimmies** 2022-02-28 00:20 UTC
Labels: duplicate
