### ISSUE TITLE
hair color

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1209] opened 2022-02-14 00:30 UTC
#### __Description__ 
hair color changes every time i fly in and out of the city, tried to save an outfit with the hair color, doesnt work
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Non Canadian Bear
**Coordinates** | vector3(107.5922, -1950.533, 20.66422)
**Steam ID** | steam:1100001078bca05
**Discord ID** | discord:175051600539287562
**Citizen ID** | YYF10312
**Character Name** | Barrett Tavares

**Comment by Dimmies** [comment] 2022-02-28 00:20
Duplicate of #630

**Closed as completed by Dimmies** 2022-02-28 00:20 UTC
Labels: duplicate
