### ISSUE TITLE
Bike towing 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#359] opened 2021-09-04 15:29 UTC
#### __Description__ 
flips the tow truck out 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | xBrodyxS
**Coordinates** | vector3(-92.77623, -1326.401, 28.85788)
**Steam ID** | steam:11000010c834ebf
**Discord ID** | discord:424994252775358465
**Citizen ID** | THQ84246
**Character Name** | Treyvon Williams

**Comment by Dimmies** [comment] 2021-09-04 20:02
Duplicate of #357

**Closed as completed by Dimmies** 2021-09-04 20:02 UTC
Labels: duplicate
