### ISSUE TITLE
Hair reverting

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1152] opened 2022-01-26 16:42 UTC
#### __Description__ 
I am now logging in everytime without fail, with the wrong hair. It's always the same hair. The one I'm supposed to log in with is 60 (grey)
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Casso
**Coordinates** | vector3(-86.36242, -2003.744, 18.01694)
**Steam ID** | steam:1100001037a1b0f
**Discord ID** | discord:188065178426933249
**Citizen ID** | ZIF94758
**Character Name** | Kieron Casso

**Comment by Dimmies** [comment] 2022-02-28 00:20
Duplicate of #630

**Closed as completed by Dimmies** 2022-02-28 00:20 UTC
Labels: duplicate
