### ISSUE TITLE
Radio 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#365] opened 2021-09-05 21:50 UTC
#### __Description__ 
Civs can't join radio channels 

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | xBrodyxS
**Coordinates** | vector3(431.9193, -982.5378, 30.7119)
**Steam ID** | steam:11000010c834ebf
**Discord ID** | discord:424994252775358465
**Citizen ID** | DAH53801
**Character Name** | Sonny Ajello

**Comment by Dimmies** [comment] 2021-09-05 22:09
Duplicate of #364

**Closed as completed by Dimmies** 2021-09-05 22:09 UTC
Labels: bug, complete
