### ISSUE TITLE
Adverts

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1450] opened 2022-05-03 22:09 UTC
#### __Description__ 
Adverts seem to stay up even when someone disconnects.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Lazrik
**Coordinates** | vector3(193.7662, -3166.973, 5.79027)
**Steam ID** | steam:1100001116d7bcc
**Discord ID** | discord:948810480535875604
**Citizen ID** | ZWP32858
**Character Name** | Curtis Prophet

**Comment by Dimmies** [comment] 2022-05-05 04:06
Duplicate of #1445

**Closed as completed by Dimmies** 2022-05-05 04:06 UTC
Labels: duplicate
