### ISSUE TITLE
i cant enter my car, this the second in 10 mins. this happened,

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#843] opened 2021-11-16 05:41 UTC
#### __Description__ 
i talked to admins and now i am mad because i just got help and i got my car and now i can't get gas because when i exit my car i can't back in.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | xoResource
**Coordinates** | vector3(2537.745, 2594.776, 37.94488)
**Steam ID** | steam:110000149a2ead2
**Discord ID** | discord:457443264166100996
**Citizen ID** | DZI28244
**Character Name** | Resource EBK

**Comment by Dimmies** [comment] 2021-11-27 00:05
Duplicate of #593

**Closed as completed by Dimmies** 2021-11-27 00:05 UTC
Labels: bug, unconfirmed
