### ISSUE TITLE
Hairstyle not staying once changed

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1219] opened 2022-02-17 02:41 UTC
#### __Description__ 
I have changed my hair- saved it with an outfit and the first day it worked and now everyday when I change to this specific character, it switches back to the hair I made her with. Quinn Silvius. I am not sure how else to make it stick- but its bothersome to have to go and change it everytime I play her. 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Vespaer
**Coordinates** | vector3(215.6584, -778.9012, 30.83496)
**Steam ID** | steam:11000011a4b3032
**Discord ID** | discord:299363685925650442
**Citizen ID** | AMO92826
**Character Name** | Quinn Silvius

**Comment by Dimmies** [comment] 2022-02-28 00:20
Duplicate of #630

**Closed as completed by Dimmies** 2022-02-28 00:20 UTC
Labels: duplicate
