### ISSUE TITLE
Weird broken  css/html stuff

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#588] opened 2021-09-26 21:02 UTC
#### __Description__ 
Just shows up as a banner across the top starting from when the character select loads.
#### __Evidence__ 
https://i.imgur.com/7Mz7z8G.jpeg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | D-reck
**Coordinates** | vector3(195.3451, -652.872, -56.97389)
**Steam ID** | steam:110000104ae2dd0
**Discord ID** | discord:114647394120892424
**Citizen ID** | MZS25831
**Character Name** | Leland James

**Comment by Dimmies** [comment] 2021-09-27 21:01
Duplicate of #459

**Closed as completed by Dimmies** 2021-09-27 21:01 UTC
Labels: duplicate
