### ISSUE TITLE
all huds missing

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#77] opened 2021-07-19 21:20 UTC
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(-2488.713, 3670.008, 13.83396)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | IEO17773
**Character Name** | Cody Ohana

**Comment by Dimmies** [comment] 2021-07-20 00:43
Duplicate of #64

**Closed by Dimmies** 2021-07-20 00:43 UTC
Labels: unconfirmed
