### ISSUE TITLE
Pulling cars out

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1057] opened 2021-12-29 20:50 UTC
#### __Description__ 
"Fixed vehicles spawning stalled/broken when retrieving from garage" - Still bugged, I pulled my car out and the engine immediately stalled and tire popped
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Murci
**Coordinates** | vector3(215.0892, -807.1732, 30.79256)
**Steam ID** | steam:11000011630e157
**Discord ID** | discord:177535063741825024
**Citizen ID** | MHX93241
**Character Name** | Joshua Reinhardt

**Comment by Dimmies** [comment] 2021-12-31 02:03
Duplicate of #976

**Closed as completed by Dimmies** 2021-12-31 02:03 UTC
Labels: duplicate
