### ISSUE TITLE
DROPPED ITEMS

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#172] opened 2021-08-14 21:06 UTC
#### __Description__ 
Random dropped items showing randlomly
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(-1115.008, -1977.118, 13.16215)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | USC02137
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment] 2021-08-14 22:45
Duplicate of #171

**Closed by Dimmies** 2021-08-14 22:45 UTC
Labels: duplicate
