### ISSUE TITLE
Car wont unlock after spinning the wheel.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#784] opened 2021-11-05 19:58 UTC
#### __Description__ 
This is the third time its happens, so I'm not sure if its just me or now. I goto the Casino, do my 5 spins, deposit money into the ATM, then walk back to my car outside. Though, when I attempt to unlock it, it will not unlock. It shows it locks, unlocks, all that, but nothing happens.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | OhNoItsEdge
**Coordinates** | vector3(909.5529, 46.39693, 80.89909)
**Steam ID** | steam:110000106bb70ad
**Discord ID** | discord:229992982093365248
**Citizen ID** | RUM31342
**Character Name** | James Edge

**Comment by Dimmies** [comment] 2021-11-06 19:15
Duplicate of #593

**Closed as completed by Dimmies** 2021-11-06 19:15 UTC
Labels: duplicate
