### ISSUE TITLE
Boss menu for Chief of ems

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#358] opened 2021-09-04 15:12 UTC
#### __Description__ 
Not working 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | xBrodyxS
**Coordinates** | vector3(334.8234, -594.0587, 43.28409)
**Steam ID** | steam:11000010c834ebf
**Discord ID** | discord:424994252775358465
**Citizen ID** | UBD72148
**Character Name** | Rudy Domino

**Comment by Dimmies** [comment] 2021-09-04 20:01
Duplicate of #352

**Closed as completed by Dimmies** 2021-09-04 20:01 UTC
Labels: duplicate
