### ISSUE TITLE
Bennys missing features

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1187] opened 2022-02-11 20:48 UTC
#### __Description__ 
going into bennys i can not change my wheels at all and a majority of custom things you can do to it have disappeared. Since the most recent update features on my car changed such as the rims and wing disappearing and being stock. So i went to bennys to fix them to find i only have 5 options.
#### __Evidence__ 
https://medal.tv/games/gta-v/clips/aFWxoPJf16Ydh/d1337woWyW0z?invite=cr-MSx6cDksMjU3NTAxOTcs
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Britamins
**Coordinates** | vector3(-34.77506, -1050.51, 27.72278)
**Steam ID** | steam:110000133272d55
**Discord ID** | discord:156579090315345920
**Citizen ID** | MHP48555
**Character Name** | Briten Clark

**Comment by Dimmies** [comment] 2022-02-11 23:22
Duplicate of #1186

**Closed as completed by Dimmies** 2022-02-11 23:22 UTC
Labels: duplicate
