### ISSUE TITLE
Mining Scuff still

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1293] opened 2022-03-13 15:35 UTC
#### __Description__ 
Bought a brand new pickaxe, went mining, HUD shows im gaining ores but am not getting any in inventory. 
#### __Evidence__ 
https://medal.tv/games/gta-v/clips/e9XRV60HUBwva/d1337mWS8G7z?invite=cr-MSx5UFosNTM0NTgwNzIs  
F8 Script: 
script: hive-nitro load nitro | Fuel: 0 
script: xsound error during NUI callback events @xsound/client/events.lua:3a attemt to index a nil value (field '?')
 script: hive-nitro Save Nitro
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Ghee
**Coordinates** | vector3(1725.189, 3712.998, 34.22132)
**Steam ID** | steam:1100001129abbd7
**Discord ID** | discord:264187574388654081
**Citizen ID** | RXH73272
**Character Name** | Bobby Bones

**Comment by Dimmies** [comment] 2022-03-15 00:12
Duplicate of #1286

**Closed as completed by Dimmies** 2022-03-15 00:12 UTC
Labels: duplicate
