### ISSUE TITLE
Sentinel Missing Bennys Items

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1188] opened 2022-02-11 20:48 UTC
#### __Description__ 
Missing a lot of customization in bennys like the wing, roof pannels, and a lot of tuning parts
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Ghee
**Coordinates** | vector3(-37.22095, -1053.295, 28.05305)
**Steam ID** | steam:1100001129abbd7
**Discord ID** | discord:264187574388654081
**Citizen ID** | RXH73272
**Character Name** | Bobby Bones

**Comment by Dimmies** [comment] 2022-02-11 23:22
Duplicate of #1186

**Closed as completed by Dimmies** 2022-02-11 23:22 UTC
Labels: duplicate
