### ISSUE TITLE
Cars in the Tuner shop are not refreshing on the set friday time

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1517] opened 2022-05-28 10:23 UTC
#### __Description__ 
(title)
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Britamins
**Coordinates** | vector3(151.7362, -3103.542, 5.891609)
**Steam ID** | steam:110000133272d55
**Discord ID** | discord:156579090315345920
**Citizen ID** | MHP48555
**Character Name** | Briten Clark

**Comment by Dimmies** [comment] 2022-07-10 21:12
Duplicate of #1514

**Closed as completed by Dimmies** 2022-07-10 21:12 UTC
Labels: duplicate
