### ISSUE TITLE
Woke up with no bullets in guns.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#887] opened 2021-11-26 08:21 UTC
#### __Description__ 
I had about 60 rounds of ammunition in the hunting rifle and about 150 for the regular pistol. When pulling them out they were both at 0. I'm not part of PD, so these guns purchased at Ammunation.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Wref
**Coordinates** | vector3(309.7945, -592.279, 43.28408)
**Steam ID** | steam:110000100bc31fe
**Discord ID** | discord:524086895911763978
**Citizen ID** | XWL36088
**Character Name** | Cliff Sawyer

**Comment by Dimmies** [comment] 2021-11-27 00:18
Duplicate of #646

**Closed as completed by Dimmies** 2021-11-27 00:18 UTC
Labels: duplicate
