### ISSUE TITLE
Ammo disappearing

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#867] opened 2021-11-21 04:29 UTC
#### __Description__ 
I lost my ammo on a pistol. I had about 95 rounds and when I pulled my weapon for the first time since like 9AM on 11/20/2021 I realized i was at 0/0 for my ammo. My F8 didnt show anything and I only can show my gun being at 0/0
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dopykoh.TTV
**Coordinates** | vector3(-1418.718, -446.6745, 35.90971)
**Steam ID** | steam:11000011376e182
**Discord ID** | discord:193681533620584448
**Citizen ID** | VJG97234
**Character Name** | Jose Fernandez

**Comment by Dimmies** [comment] 2021-11-27 00:19
Duplicate of #646

**Closed as completed by Dimmies** 2021-11-27 00:19 UTC
Labels: duplicate
