### ISSUE TITLE
Lumber bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1323] opened 2022-03-26 16:08 UTC
#### __Description__ 
At times when a tree is cut down, the ground swallows up the logs when the tree hits the ground and breaks into logs.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-524.0638, 5175.781, 91.18697)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment] 2022-03-26 16:33
This seems to be on uneven ground-which most of it is.

**Comment by Dimmies** [comment] 2022-04-11 03:43
Duplicate of #1210

**Closed as completed by Dimmies** 2022-04-11 03:43 UTC
Labels: duplicate
