### ISSUE TITLE
Facial settings reset everytime I log in.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#935] opened 2021-12-03 17:02 UTC
#### __Description__ 
All facial set settings are reset even after saving them at plastic surgery. for exampe i spawn with a max butt chin, tiny nose, and skinny neck among other settings not staying put.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Britamins
**Coordinates** | vector3(304.4521, -588.2964, 43.2841)
**Steam ID** | steam:110000133272d55
**Discord ID** | discord:156579090315345920
**Citizen ID** | MHP48555
**Character Name** | Briten Clark

**Comment by Dimmies** [comment] 2022-01-14 01:03
Duplicate of #893

**Closed as completed by Dimmies** 2022-01-14 01:03 UTC
Labels: duplicate
