### ISSUE TITLE
court house broken

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1328] opened 2022-03-27 00:52 UTC
#### __Description__ 
interior for the courthouse is all scuffed
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Tashells
**Coordinates** | vector3(236.0111, -411.7163, 47.93098)
**Steam ID** | steam:1100001080d9f37
**Discord ID** | discord:667668359198015499
**Citizen ID** | QOT21414
**Character Name** | Rosa Martinez

**Comment by Dimmies** [comment] 2022-03-28 17:36
Duplicate of #1327

**Closed as completed by Dimmies** 2022-03-28 17:36 UTC
Labels: duplicate
