### ISSUE TITLE
CAR TRACKING

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#508] opened 2021-09-19 12:39 UTC
#### __Description__ 
tracking app is not working for me. just says my cars are in the garage

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Silver_Twist86
**Coordinates** | vector3(230.1335, -797.1729, 30.20937)
**Steam ID** | steam:110000104ca4df2
**Discord ID** | discord:215280083957448704
**Citizen ID** | JRX14884
**Character Name** | Bryan Stone

**Comment by Dimmies** [comment] 2021-09-20 04:31
Duplicate of #507

**Closed as completed by Dimmies** 2021-09-20 04:31 UTC
Labels: duplicate
