### ISSUE TITLE
Steel Pickaxe continued.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1284] opened 2022-03-11 22:59 UTC
#### __Description__ 
Per previous report, I noticed the pickaxe that does not produce material also does not display a 'uses left' when in inventory.
#### __Evidence__ 
https://i.imgur.com/8ao4sUs.png https://i.imgur.com/yOuBJu6.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | JazyPickle
**Coordinates** | vector3(2947.111, 2734.146, 45.04944)
**Steam ID** | steam:1100001084f8daa
**Discord ID** | discord:303249267403915274
**Citizen ID** | GFU48929
**Character Name** | Jim Packle

**Comment by Dimmies** [comment] 2022-03-15 00:31
Duplicate of #1286

**Closed as completed by Dimmies** 2022-03-15 00:31 UTC
Labels: duplicate
