### ISSUE TITLE
More vehicle lock problems

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#774] opened 2021-11-04 01:51 UTC
#### __Description__ 
26epr714 would not unlock. Would not unlock after slimjimmed. DV'd the car but did not go into garage, had to storeplate. Was working after taken back out.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1412.052, -426.5189, 35.63866)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment] 2021-11-04 17:52
Duplicate of #593

**Closed as completed by Dimmies** 2021-11-04 17:52 UTC
Labels: duplicate
