### ISSUE TITLE
Player Car Despawn

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#319] opened 2021-08-30 03:03 UTC
#### __Description__ 
Car desapwned and is listed as "out" at the garage. 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(226.863, -804.0759, 30.6704)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment] 2021-09-01 21:05
Duplicate of #248

**Closed as completed by Dimmies** 2021-09-01 21:05 UTC
Labels: duplicate
