### ISSUE TITLE
Hair still changes back even after saving

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1370] opened 2022-04-10 20:59 UTC
#### __Description__ 
My hair has changed back to a style that I had prior multiple times and even after saving the entire look/outfit with the hairstyle I'm wanting- it still reverts back and it's only on one character that this happens to. Everyone else stays the same if I change it up, but Khalia is always fucked. LOL
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Anjie
**Coordinates** | vector3(219.0254, -810.5679, 30.66427)
**Steam ID** | steam:1100001074928e6
**Discord ID** | discord:262828827049197568
**Citizen ID** | RML13468
**Character Name** | Khalia Hawthorne

**Comment by Dimmies** [comment] 2022-04-10 22:39
Duplicate of #630

**Closed as completed by Dimmies** 2022-04-10 22:39 UTC
Labels: duplicate
