### ISSUE TITLE
Gas Can Didn't Work

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#415] opened 2021-09-10 22:18 UTC
#### __Description__ 
I filled Bryans car up with fuel from teh gas can and it worked in my eyes but when he got in it was back to the original 17%. Then when I got in (after he had already been in it before me) I also saw the 17% - I should have got in the vehicle before and after filling it up but I only realised this with hindsight.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chuff
**Coordinates** | vector3(-84.63699, -1329.646, 29.29218)
**Steam ID** | steam:110000101c301ed
**Discord ID** | discord:147386472016642058
**Citizen ID** | FHO94294
**Character Name** | Tommy Jenkins

**Comment by Dimmies** [comment] 2021-09-13 07:07
Duplicate of #423

**Closed as completed by Dimmies** 2021-09-13 07:07 UTC
Labels: duplicate
