### ISSUE TITLE
missing UI from phone

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1098] opened 2022-01-10 08:48 UTC
#### __Description__ 
Pulling up the phone theres no background or content in texts
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Britamins
**Coordinates** | vector3(246.8454, -604.8258, 41.92499)
**Steam ID** | steam:110000133272d55
**Discord ID** | discord:156579090315345920
**Citizen ID** | MHP48555
**Character Name** | Briten Clark

**Comment by Dimmies** [comment] 2022-02-27 23:49
Duplicate of #716

**Closed as completed by Dimmies** 2022-02-27 23:49 UTC
Labels: duplicate
