### ISSUE TITLE
Car HUD

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#76] opened 2021-07-19 21:14 UTC
#### __Description__ 
Can't see the car hud anymore whilst driving.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | LazrikOnTwitch
**Coordinates** | vector3(2641.327, 487.2333, 95.41683)
**Steam ID** | steam:1100001116d7bcc
**Discord ID** | discord:360933761849884674
**Citizen ID** | FMJ88099
**Character Name** | Vitor Primo

**Comment by Dimmies** [comment] 2021-07-20 00:43
Duplicate of #64

**Closed** 2021-07-20 00:42 UTC
Labels: unconfirmed
