### ISSUE TITLE
underpaid off duty.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1006] opened 2021-12-15 22:24 UTC
#### __Description__ 
Still getting paid $10 instead of $25 whilst off duty.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Artemis1290
**Coordinates** | vector3(-533.2573, -1213.607, 18.18485)
**Steam ID** | steam:1100001322df320
**Discord ID** | discord:364076542575247360
**Citizen ID** | HFB40197
**Character Name** | Andrew Castle

**Comment by Dimmies** [comment] 2021-12-16 01:36
Duplicate of #986

**Closed as completed by Dimmies** 2021-12-16 01:36 UTC
Labels: bug, duplicate
