### ISSUE TITLE
Can't get in car

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#822] opened 2021-11-13 00:42 UTC
#### __Description__ 
Follow up can't get in car again when unlocked but can access trunk.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1411.928, -425.0878, 36.1819)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment] 2021-11-13 06:00
Advanced lockpick seems to solve the problem until a fix can be had.

**Comment by Dimmies** [comment] 2021-11-27 00:01
Duplicate of #593

**Closed as completed by Dimmies** 2021-11-27 00:01 UTC
Labels: duplicate
