### ISSUE TITLE
Apt

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#240] opened 2021-08-20 02:44 UTC
#### __Description__ 
No prompt in elevvater to go to apt. Also Cody and I were in the same apt.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(284.2847, -652.9861, 42.01862)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by Dimmies** [comment] 2021-08-21 19:05
Duplicate of #210

**Closed as completed by Dimmies** 2021-08-21 19:05 UTC
Labels: duplicate
