### ISSUE TITLE
Items on the ground stay after being picked up

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#368] opened 2021-09-05 23:53 UTC
#### __Description__ 
I dropped a food item on the ground and it was picked up, but the icon remained as shown the screenshot. There is nothing in there at all
#### __Evidence__ 
https://i.imgur.com/9PAjQWh.jpeg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dirgia
**Coordinates** | vector3(304.8137, -585.5824, 43.28406)
**Steam ID** | steam:110000103f9c1d5
**Discord ID** | discord:194461233410211840
**Citizen ID** | FEC98698
**Character Name** | Karen Rainer

**Comment by Dimmies** [comment] 2021-09-06 02:21
Duplicate of #362

**Closed as completed by Dimmies** 2021-09-06 02:21 UTC
Labels: duplicate
