### ISSUE TITLE
Phone 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#678] opened 2021-10-18 08:55 UTC
#### __Description__ 
After opening yellow page i went to tweeter and now i see both app together.
#### __Evidence__ 
https://cdn.discordapp.com/attachments/709783994677329921/899581129982627860/unknown.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Grumpy Panda
**Coordinates** | vector3(-1174.154, -1581.665, 4.331796)
**Steam ID** | steam:1100001361b9d6d
**Discord ID** | discord:398117627442233346
**Citizen ID** | KCL77910
**Character Name** | James Famingo

**Comment by Dimmies** [comment] 2021-11-02 20:33
Duplicate of #615

**Closed as completed by Dimmies** 2021-11-02 20:33 UTC
Labels: duplicate
