### ISSUE TITLE
Silent Gunshots

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#738] opened 2021-10-29 08:11 UTC
#### __Description__ 
No gunshot audio in Casino
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Safefield
**Coordinates** | vector3(973.972, 46.63913, 74.47624)
**Steam ID** | steam:110000106d6e53c
**Discord ID** | discord:189895867489189888
**Citizen ID** | ZHD76011
**Character Name** | RJ Safefield

**Comment by Dimmies** [comment] 2021-10-29 20:49
Duplicate of #721

**Closed as completed by Dimmies** 2021-10-29 20:49 UTC
Labels: duplicate
