### ISSUE TITLE
YP ads still being up

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1478] opened 2022-05-08 10:05 UTC
#### __Description__ 
Yellow Page ads are still showing even though the person who put them up is no longer in the city.
#### __Evidence__ 
https://cdn.discordapp.com/attachments/733227536535781478/972801439200067635/unknown.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Anjie
**Coordinates** | vector3(75.08353, -1280.53, 28.44539)
**Steam ID** | steam:1100001074928e6
**Discord ID** | discord:262828827049197568
**Citizen ID** | RML13468
**Character Name** | Khalia Hawthorne

**Comment by Dimmies** [comment] 2022-05-20 19:12
Duplicate of #1445

**Closed as completed by Dimmies** 2022-05-20 19:12 UTC
Labels: duplicate
