### ISSUE TITLE
Cars damaged when getting it out of garage

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1055] opened 2021-12-29 03:55 UTC
#### __Description__ 
everytime you grab a car out of the garage, it breaks the windows and tires.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | DimBagDimez
**Coordinates** | vector3(243.0588, -661.5814, 38.23727)
**Steam ID** | steam:110000141b3085e
**Discord ID** | discord:712785321481469994
**Citizen ID** | NQP90955
**Character Name** | Dimez DAmico

**Comment by Dimmies** [comment] 2021-12-31 02:02
Duplicate of #976

**Closed as completed by Dimmies** 2021-12-31 02:02 UTC
Labels: duplicate
