### ISSUE TITLE
CAN'T STORE MOTORCYCLE

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#839] opened 2021-11-16 01:40 UTC
#### __Description__ 
Cannot store my NRG900F motorcycle 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Ronnie Gurthman
**Coordinates** | vector3(2.769851, -1874.974, 23.23699)
**Steam ID** | steam:11000010766b926
**Discord ID** | discord:473296664371658752
**Citizen ID** | PVC91827
**Character Name** | Damian Carter

**Comment by Dimmies** [comment] 2021-11-27 00:04
Duplicate of #419

**Closed as completed by Dimmies** 2021-11-27 00:04 UTC
Labels: duplicate
