### ISSUE TITLE
Car Damage on Spawn

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1054] opened 2021-12-28 19:05 UTC
#### __Description__ 
Alwyn reported in suggestions 
Alwyn#3170
Suggestion
Look into a different way to store and/or spawn in vehicles? The current setup is causing vehicle damage like popping a tire and making the engine smoke.
Current Status
OPEN
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-78.16548, -655.3132, -56.97388)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment] 2021-12-31 02:02
Duplicate of #976

**Closed as completed by Dimmies** 2021-12-31 02:02 UTC
Labels: duplicate
