### ISSUE TITLE
House Decor disappearing

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#888] opened 2021-11-26 08:28 UTC
#### __Description__ 
So I spent about three hours decorating the house I just got. I had gone in and out of it prior, and it all stayed. For some reason, I came back inside and most of it was gone. I then relogged, shutting down FiveM entirely and still the items didn't return. So then I waited for the next restart, hoping things would return and they did not- as well as the few items that had stayed were gone. So I was back to a bare house. 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Vespaer
**Coordinates** | vector3(1386.807, -1542.689, 29.2608)
**Steam ID** | steam:11000011a4b3032
**Discord ID** | discord:299363685925650442
**Citizen ID** | FKX31546
**Character Name** | Raeya Calloway

**Comment by Dimmies** [comment] 2021-11-27 00:18
Duplicate of #859

**Closed as completed** 2022-01-13 12:21 UTC
Labels: duplicate, complete
