### ISSUE TITLE
Character rest at Barber Shop

### ISSUE THREAD

**Issue by eamundson1** [TheHiveRP/HiveIssues#366] opened 2021-09-05 22:39 UTC
**Describe the bug**
FYI
Went to the barber shop and went through selections. Ended up not changing anything and exiting. Upon exiting I was a default ped with default clothes. I went to the clothing shop but nothing changed. 
I then went to my apartment and chose my saved outfit. The clothes changed to the correct outfit but character remained default. I didn't want the character saved so I exited game by using ctrl alt delete. Came back in game and everything was rest to normal.
Didn't see any errors.

**Comment by Dimmies** [comment] 2021-09-05 23:57
Duplicate of #363

**Closed as completed by Dimmies** 2021-09-05 23:57 UTC
Labels: duplicate
