### ISSUE TITLE
Mining issue (cont)

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1297] opened 2022-03-14 14:33 UTC
#### __Description__ 
When mining using a steel pickaxe (with uses being counted on pickaxe), materials shown being collected but do not go into inventory. 
#### __Evidence__ 
https://clips.twitch.tv/BoldColdSwanCeilingCat-7DiT7rm3HIRi1Tsb
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | JazyPickle
**Coordinates** | vector3(482.4422, -348.2079, 45.6469)
**Steam ID** | steam:1100001084f8daa
**Discord ID** | discord:303249267403915274
**Citizen ID** | GFU48929
**Character Name** | Jim Packle

**Comment by Dimmies** [comment] 2022-03-15 00:11
Duplicate of #1286

**Closed as completed by Dimmies** 2022-03-15 00:11 UTC
Labels: duplicate
