### ISSUE TITLE
Missing Parts

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1190] opened 2022-02-11 21:28 UTC
#### __Description__ 
Flew back into the city after Tsunami/flood, and when I retrieved my SG4 out of my garage, everything aftermarket on my vehicle was swapped out for stock parts. Livery, wheels, paint, etc, all of it is now completely gone. 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Karl
**Coordinates** | vector3(-80.13349, -1026.836, 27.99615)
**Steam ID** | steam:1100001126e7c68
**Discord ID** | discord:312768274389532673
**Citizen ID** | AUR15450
**Character Name** | Matt Lekowski

**Comment by Dimmies** [comment] 2022-02-11 23:22
Duplicate of #1186

**Closed as completed by Dimmies** 2022-02-11 23:22 UTC
Labels: duplicate
