### ISSUE TITLE
Inventory wont open 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#468] opened 2021-09-15 11:12 UTC
#### __Description__ 
ive done the restarts and relogged but still nothing shows with f2
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | photog0510
**Coordinates** | vector3(30.36853, -1358.14, 29.28314)
**Steam ID** | steam:11000013e0a6e14
**Discord ID** | discord:521065052904882189
**Citizen ID** | SZO16810
**Character Name** | Taylor Burns

**Comment by Dimmies** [comment] 2021-09-16 02:08
Duplicate of #467

**Closed as completed by Dimmies** 2021-09-16 02:08 UTC
Labels: duplicate
