### ISSUE TITLE
Character Creation

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1065] opened 2021-12-31 00:43 UTC
#### __Description__ 
When attempting to choose a ped as a character it freezes on the second choice(traffic warden) and will not move either direction. This also freezes all other customization choices. The character then has to be deleted later. Eddie also had this problem. I saw no erros.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1976.482, -529.0764, 11.87169)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment] 2022-01-09 05:11
Duplicate of #1050

**Closed as completed by Dimmies** 2022-01-09 05:11 UTC
Labels: duplicate
