### ISSUE TITLE
Cellphone background and apps

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1221] opened 2022-02-18 05:00 UTC
#### __Description__ 
Cellphone background is transparent and all the apps have '0' on them as though they had notifications.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | EDMDillon
**Coordinates** | vector3(-105.7892, -653.5945, -56.97388)
**Steam ID** | steam:110000109ef001b
**Discord ID** | discord:822250202479853568
**Citizen ID** | ALN44792
**Character Name** | Scarlet Shepard

**Comment by Dimmies** [comment] 2022-02-28 00:09
Duplicate of #716

**Closed as completed by Dimmies** 2022-02-28 00:09 UTC
Labels: duplicate
