### ISSUE TITLE
Ended up in some other players apartment.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#631] opened 2021-10-05 16:31 UTC
#### __Description__ 
Took the elevator in to my apartment and there is a dude standing here.
#### __Evidence__ 
Didn't know I need to take a screenshot, but I will next time
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Max
**Coordinates** | vector3(-109.7066, -654.8854, -56.92728)
**Steam ID** | steam:11000013699bedc
**Discord ID** | discord:749761396996047001
**Citizen ID** | CCC06524
**Character Name** | Miu Bratislava

**Comment by Dimmies** [comment] 2021-10-10 05:38
Duplicate of #562

**Closed as completed** 2021-10-10 05:38 UTC
Labels: duplicate
