### ISSUE TITLE
towing

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#402] opened 2021-09-10 00:27 UTC
#### __Description__ 
went to tow a car and it would not connect to the tow truck. did get winched onto the bed just didnt attach to truck

#### __Evidence__ 
no F8 errors
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Silver_Twist86
**Coordinates** | vector3(2699.978, 4698.566, 44.3798)
**Steam ID** | steam:110000104ca4df2
**Discord ID** | discord:215280083957448704
**Citizen ID** | JRX14884
**Character Name** | Bryan Stone

**Comment by Dimmies** [comment] 2021-09-10 00:39
Duplicate of #370

**Closed as completed by Dimmies** 2021-09-10 00:39 UTC
Labels: bug, complete
