### ISSUE TITLE
Car occasionally failing to be stored in the garage

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#857] opened 2021-11-18 02:38 UTC
#### __Description__ 
Tried to put car away after taking it out at Legion Garage and it wouldn't store.
#### __Evidence__ 
https://i.imgur.com/tFFeX2r.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | NadeFrame
**Coordinates** | vector3(259.5741, -748.0341, 30.81969)
**Steam ID** | steam:110000110adcb80
**Discord ID** | discord:262487501434912768
**Citizen ID** | DGV32947
**Character Name** | Malique Hendrix

**Comment by Dimmies** [comment] 2021-11-27 00:07
Duplicate of #419

**Closed as completed by Dimmies** 2021-11-27 00:07 UTC
Labels: duplicate
