### ISSUE TITLE
Trunk

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#556] opened 2021-09-24 09:36 UTC
#### __Description__ 
Getting into the trunk makes you just stand in the trunk and can't get out without begin carried
#### __Evidence__ 
no f8, cant clip but 2 hours in twitch.tv/GhostieBoi97 stream
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Buddha
**Coordinates** | vector3(-1072.585, -1281.025, 5.97488)
**Steam ID** | steam:110000116dc7db7
**Discord ID** | discord:304578653667459073
**Citizen ID** | LEP29163
**Character Name** | Laroi Padrino

**Comment by Dimmies** [comment] 2021-10-10 05:39
Duplicate of #545

**Closed as completed by Dimmies** 2021-10-10 05:39 UTC
Labels: duplicate
