### ISSUE TITLE
APARTMENTS

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#397] opened 2021-09-09 20:04 UTC
#### __Description__ 
everyone is in the same apartment when they enter. means you see everyone
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | VisionzAx
**Coordinates** | vector3(285.0216, -651.0728, -16.97389)
**Steam ID** | steam:110000136d79dfe
**Discord ID** | discord:527475418299629568
**Citizen ID** | BRI89099
**Character Name** | Kilo Broker

**Comment by Dimmies** [comment] 2021-09-09 21:02
Duplicate of #375

**Closed as completed by Dimmies** 2021-09-09 21:02 UTC
Labels: duplicate
