### ISSUE TITLE
Civilian Added Armor

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#860] opened 2021-11-18 07:52 UTC
#### __Description__ 
When smoking meth to add to your armor on a civilian, the added armor does not save when you disconnect & reconnect to the server.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuz
**Coordinates** | vector3(223.6586, -729.7184, 34.46093)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | BFV40301
**Character Name** | Andre Turner

**Comment by Dimmies** [comment] 2021-11-27 00:41
Duplicate of #870

**Closed as completed by Dimmies** 2021-11-27 00:41 UTC
Labels: duplicate
