### ISSUE TITLE
Parts are not degrading 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#885] opened 2021-11-25 17:29 UTC
#### __Description__ 
Someone came by Hayes and said they drive their car everyday for a long time and the parts are all at 100%. They never have had parts replaced.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dopykoh.TTV
**Coordinates** | vector3(-1420.941, -445.2918, 35.90971)
**Steam ID** | steam:11000011376e182
**Discord ID** | discord:193681533620584448
**Citizen ID** | VJG97234
**Character Name** | Jose Fernandez

**Comment by Dimmies** [comment] 2021-11-27 00:17
Duplicate of #879

**Closed as completed by Dimmies** 2021-11-27 00:17 UTC
Labels: duplicate
